/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Controller.warObservable;
import jaco.mp3.player.MP3Player;
import java.io.File;
import javax.swing.Timer;

/**
 *
 * @author nipun
 */
public class Home extends javax.swing.JFrame {
    
    private Timer timer;
    private MP3Player player;

    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setTitle("Defence System");

        setupPlayer();
        setupTimer();
    }

    private void setupPlayer() {
        player = new MP3Player(new File("E:\\04 OOP\\Courseworks\\Final Coursework\\DefenseSystem\\Accets\\MP3\\DefenseSystem.MP3"));
        player.play();
    }

    private void setupTimer() {
        timer = new Timer(14000, e -> {
            runGame();
        });
        timer.setRepeats(false);
        timer.start();
    }
    
    private void runGame() {
        if (timer != null) {
            timer.stop();
        }
        if (player != null) {
            player.stop();
        }
        setupGameComponents();
        this.dispose();
    }

    private void setupGameComponents() {
        warObservable ob = new warObservable();
        MainController main = MainController.getInstance();

        ob.addToWarArray(new Helicopter());
        ob.addToWarArray(new Tank());
        ob.addToWarArray(new Submarine());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\04 OOP\\Courseworks\\Final Coursework\\DefenseSystem\\Accets\\Images\\startButton.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 580, 160, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\04 OOP\\Courseworks\\Final Coursework\\DefenseSystem\\Accets\\Videos\\DefenseSystem_9.gif")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        runGame();
    }//GEN-LAST:event_jLabel2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
